# code: language=TOML insertSpaces=true tabSize=2

[install]
command = "cargo"
args = ["install",  "--path",  "."]

[install.post]
command = "bash"
args = ["-c", "cp -fav ~/.cargo/bin/doit ~/bin/doit"]
