# code: language=TOML insertSpaces=true tabSize=2

[install]
command = "cargo"
exe = "bin/doit"
cargo-do = "bin/cargo-do"
args = ["install",  "--path",  "."]
post = [
  ["bash", "-c", "cp -fav ~/.cargo/%exe% ~/%exe%"],
  ["bash", "-c", "cp -fav ~/.cargo/%exe% ~/%cargo-do%"]
]

[clear-dot-cargo]
command = "bash"
dir = "~/.cargo"
args = ["-c",  "rm -rf %dir%"]
pre = [["bash", "-c", "du -hs %dir%"]]
post = [
    [
      "bash", "-c",
      '''
        if [ -d %dir% ]; then
          file %dir%
          echo fail
          exit 1
        else
          echo ok
        fi
      '''
    ],
]
