# code: language=TOML insertSpaces=true tabSize=2

[install]
command = ["cargo", "install",  "--path",  "."]

exe = "bin/doit"
cargo-do = "~dwight/bin/cargo-do"

post = [
  ["cp", "-fav", ":~/.cargo/!{exe}", ":~/!{exe}"],
  ["cp", "-fav", ":~/.cargo/!{exe}", ":!{cargo-do}"],
]

[clear-dot-cargo]
command = ["rm", "-rf", ":!{dir}"]

dir = "~/.cargo"
pre = [["du", "-hs", ":!{dir}"]]
post = [["test", "!", "-d", ":!{dir}"]]

[whoami]
command = ["echo", ":!{env:USER}"]

[env-test]
command = ["echo", ":!{env:UNKOWN:ok}"]

[fail1]
command = ["ls", "-l"]

post = [["ls", "/NONE" ]]

[fail2]
command = ["ls", "/NONE"]

[fail3]
command = "/NONE"

[fail4]
command = ["/NONE"]
boo = [":boo", "cow"]
