# code: language=TOML insertSpaces=true tabSize=2

[install]
command = "cargo"
args = ["install",  "--path",  "."]
exe = "bin/doit"
cargo-do = "~/bin/cargo-do"
post = [
  ["cp", "-fav", "~/.cargo/!{exe}", "~/!{exe}"],
  ["cp", "-fav", "~/.cargo/!{exe}", "!{cargo-do}"],
]

[clear-dot-cargo]
command = "rm"
dir = "~/.cargo"
args = ["-rf", "!{dir}"]
pre = [["du", "-hs", "!{dir}"]]
post = [["test", "!!", "-d", "!{dir}"]]

[whoami]
command = "echo"
args = ["!{env:USER}"]

[env-test]
command = "echo"
args = ["!{env:UNKOWN:ok}"]

[fail1]
command = "ls"
args = ["-l"]

post = [["ls", "/NONE" ]]

[fail2]
command = "ls"
args = ["/NONE"]

[fail3]
command = "/NONE"
